// Generated by CoffeeScript 1.6.3
(function() {
  var dominantTemplate, minorityTemplate, people, y;

  dominantTemplate = "<strong>{{group}}</strong> earn the <strong>most</strong>.";

  minorityTemplate = "<strong>{{group}}</strong> earn <strong>{{centsOnDollar}} cents</strong> for every <strong>dollar</strong> White men earn.";

  people = {
    data: {
      men: {
        africanAmerican: 73,
        hispanic: 61,
        white: 100
      },
      women: {
        africanAmerican: 64,
        hispanic: 54,
        white: 78
      }
    },
    text: {
      men: {
        africanAmerican: "African-American men",
        hispanic: "Hispanic men",
        white: "White men"
      },
      women: {
        africanAmerican: "African-American women",
        hispanic: "Hispanic women",
        white: "White women"
      }
    }
  };

  y = d3.scale.linear().domain([0, 100]).range([0, 400]);

  $(function() {
    var divElement, explanatoryElement, selectedLeft, selectedRight, updateChart;
    selectedLeft = $("div.people table td.selected.left");
    selectedRight = $("div.people table td.selected.right");
    divElement = $(".chart div");
    explanatoryElement = $(".explanatory-text.right p");
    updateChart = function() {
      var datum, gender, genderedData, genderedText, race, text;
      gender = $(selectedRight).attr("id");
      genderedData = gender === "men" ? people.data.men : people.data.women;
      genderedText = gender === "men" ? people.text.men : people.text.women;
      race = $(selectedLeft).attr("id");
      datum = race === "white" ? genderedData.white : race === "african-american" ? genderedData.africanAmerican : genderedData.hispanic;
      text = race === "white" ? genderedText.white : race === "african-american" ? genderedText.africanAmerican : genderedText.hispanic;
      $(divElement).animate({
        height: y(datum) + "px"
      }, 500);
      $(divElement).text(datum + "%");
      return $(explanatoryElement).html(function() {
        var template;
        template = text === "White men" ? dominantTemplate : minorityTemplate;
        return Mustache.to_html(template, {
          group: text,
          centsOnDollar: datum
        });
      });
    };
    updateChart();
    $("div.people table td.left").click(function() {
      $(selectedLeft).removeClass("selected");
      $(this).addClass("selected");
      selectedLeft = this;
      return updateChart();
    });
    return $("div.people table td.right:not(.empty)").click(function() {
      $(selectedRight).removeClass("selected");
      $(this).addClass("selected");
      selectedRight = this;
      return updateChart();
    });
  });

}).call(this);
